### ISSUE TITLE
building the test-db container fails at mktemp on os 10.9

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera-images#1]
djacobs@hayek:hera-images (master)$ test-db/build.sh 
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix

**Comment by pkgw** [comment]
Should be fixed as of [commit d10c73d](https://github.com/HERA-Team/hera-images/commit/d10c73d00e3eca46911bf4b6e55fee711529498e)
